---
- hosts: localhost
  user: dhoffman
  connection: local

  vars_files:
    - vars/private.yml

  tasks:
    - include: tasks/base.yml
    - include: tasks/dotfiles.yml
    - include: tasks/install.yml
    - include: tasks/config.yml
    - include: tasks/tarsnap.yml
      when: ansible_hostname == 'Davids-Mac-Mini'
    - include: tasks/keepassx.yml
