---
- hosts: localhost
  user: dhoffman
  connection: local

  tasks:
    - include: tasks/dotfiles.yml
    - include: tasks/install.yml
    - include: tasks/config.yml
    - include: tasks/bittorrent-sync.yml