---

- name: installing pip items
  pip: name={{ item }}
  sudo: yes
  with_items:
    - virtualenv
    - virtualenvwrapper

- name: install brew cask
  command: brew install caskroom/cask/brew-cask creates=/usr/local/Cellar/brew-cask

- name: installing brew items
  homebrew: name={{ item }}
  with_items:
    - htop
    - tree

- name: installing emacs
  homebrew: name=emacs options=cocoa

- name: installing brew cask items
  homebrew_cask: name={{ item }}
  with_items:
    - adium
    - dbvisualizer
    - firefox
    - flash
    - flux
    - google-chrome
    - java
    - pycharm
